/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.Home;
import Syncronisation.Syncroniser;
import java.awt.Color;

/**
 *
 * @author honore
 */

public class Anamnese extends javax.swing.JPanel {

    /**
     * Creates new form Anamnese
     */
     Syncroniser en= new Syncroniser();
    public Anamnese()
    {
        initComponents();
      jPanel1.setBackground(new Color(54, 175, 231));
      jPanel2.setBackground(new Color(54, 175, 231));
      //jPanel2.setBackground(new Color(192, 192, 255));
      en.chargementdetail(code_pers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jcheck2 = new javax.swing.JCheckBox();
        Jcheck3 = new javax.swing.JCheckBox();
        jcheck1 = new javax.swing.JCheckBox();
        Jcheck4 = new javax.swing.JCheckBox();
        jcheck6 = new javax.swing.JCheckBox();
        Jcheck5 = new javax.swing.JCheckBox();
        JCheck9 = new javax.swing.JCheckBox();
        JCheck10 = new javax.swing.JCheckBox();
        jCheck8 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        environ = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        antecedent = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        complement = new javax.swing.JTextArea();
        mois9 = new javax.swing.JTextField();
        mois3 = new javax.swing.JTextField();
        mois6 = new javax.swing.JTextField();
        mois2 = new javax.swing.JTextField();
        mois24 = new javax.swing.JTextField();
        dat3 = new javax.swing.JTextField();
        dat2 = new javax.swing.JTextField();
        dat1 = new javax.swing.JTextField();
        jtxtlot2 = new javax.swing.JTextField();
        jtxtlot3 = new javax.swing.JTextField();
        jtxtLot1 = new javax.swing.JTextField();
        jtxtlot8 = new javax.swing.JTextField();
        dat6 = new javax.swing.JTextField();
        dat4 = new javax.swing.JTextField();
        jtxt10 = new javax.swing.JTextField();
        histoire = new javax.swing.JTextField();
        dat9 = new javax.swing.JTextField();
        dat7 = new javax.swing.JTextField();
        jtxtlot7 = new javax.swing.JTextField();
        dat5 = new javax.swing.JTextField();
        dat8 = new javax.swing.JTextField();
        jtxtlot9 = new javax.swing.JTextField();
        jtxtlot10 = new javax.swing.JTextField();
        mois12 = new javax.swing.JTextField();
        code_pers = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jtxtlot5 = new javax.swing.JTextField();
        circonstance = new javax.swing.JTextField();
        motif = new javax.swing.JTextField();
        alimentation = new javax.swing.JTextField();
        suivie = new javax.swing.JTextField();
        ida = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "INFORMATION SUR LA VACCINATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VACCINATION");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 30));

        jcheck2.setForeground(new java.awt.Color(0, 0, 204));
        jcheck2.setText("BCG");
        jcheck2.setOpaque(false);
        jPanel2.add(jcheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 40));

        Jcheck3.setForeground(new java.awt.Color(0, 0, 204));
        Jcheck3.setText("DTC-HepB-Bib 2");
        Jcheck3.setOpaque(false);
        jPanel2.add(Jcheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 40));

        jcheck1.setForeground(new java.awt.Color(0, 0, 204));
        jcheck1.setText("Pneumo 2");
        jcheck1.setOpaque(false);
        jPanel2.add(jcheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 40));

        Jcheck4.setForeground(new java.awt.Color(0, 0, 204));
        Jcheck4.setText("VPOb 0");
        Jcheck4.setOpaque(false);
        jPanel2.add(Jcheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 40));

        jcheck6.setForeground(new java.awt.Color(0, 0, 204));
        jcheck6.setText("VPOb 1");
        jcheck6.setOpaque(false);
        jPanel2.add(jcheck6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 40));

        Jcheck5.setForeground(new java.awt.Color(0, 0, 204));
        Jcheck5.setText("VPI 3");
        Jcheck5.setOpaque(false);
        jPanel2.add(Jcheck5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 40));

        JCheck9.setForeground(new java.awt.Color(0, 0, 204));
        JCheck9.setText("VPOb 2");
        JCheck9.setOpaque(false);
        jPanel2.add(JCheck9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 110, 40));

        JCheck10.setForeground(new java.awt.Color(0, 0, 204));
        JCheck10.setText("VAR");
        JCheck10.setOpaque(false);
        jPanel2.add(JCheck10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 50, 40));

        jCheck8.setForeground(new java.awt.Color(0, 0, 204));
        jCheck8.setText("DTC-HepB-Bib 3");
        jCheck8.setOpaque(false);
        jPanel2.add(jCheck8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 110, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Developpement psyco-moteur:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("ANTECEDENT");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, -1));

        environ.setColumns(20);
        environ.setForeground(new java.awt.Color(0, 0, 204));
        environ.setRows(5);
        environ.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(43, 57, 93))); // NOI18N
        jScrollPane1.setViewportView(environ);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 980, 76));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Environnement de l'enfant:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 20));

        antecedent.setColumns(20);
        antecedent.setRows(5);
        antecedent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(43, 57, 93))); // NOI18N
        jScrollPane2.setViewportView(antecedent);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 980, 50));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("COMPLEMENT D'ANAMENESE");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 180, 20));

        complement.setColumns(20);
        complement.setRows(5);
        complement.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(43, 57, 93))); // NOI18N
        jScrollPane3.setViewportView(complement);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 980, 50));

        mois9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois9, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 310, 250, -1));

        mois3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, -1));

        mois6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois6, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 270, 250, -1));

        mois2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, -1));

        mois24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 300, -1));

        dat3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 40));

        dat2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 40));

        dat1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 40));

        jtxtlot2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 40));

        jtxtlot3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 40));

        jtxtLot1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtLot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 40));

        jtxtlot8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, 40));

        dat6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 110, -1));

        dat4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 40));

        jtxt10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 150, 40));

        histoire.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Histoire de la maladie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(histoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 190, 40));

        dat9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        dat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dat9ActionPerformed(evt);
            }
        });
        jPanel2.add(dat9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 140, 40));

        dat7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, -1));

        jtxtlot7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 150, 40));

        dat5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, -1));

        dat8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(dat8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 110, -1));

        jtxtlot9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 170, 40));

        jtxtlot10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 40));

        mois12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "24 mois:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(mois12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 300, -1));

        code_pers.setEditable(true);
        code_pers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        code_pers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                code_persMouseClicked(evt);
            }
        });
        jPanel2.add(code_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 40));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Enregister");
        jLabel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 150, 40));

        jtxtlot5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Lot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel2.add(jtxtlot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 130, 40));

        circonstance.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Circontance d'acouchement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(circonstance, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 170, 40));

        motif.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motif de consultation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(motif, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 170, 40));

        alimentation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alimenttation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(alimentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 190, 40));

        suivie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suivie de grossèsse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(suivie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 190, 40));
        jPanel2.add(ida, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 14, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 650));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        String pn, bc, dt, vpo, vpi, vpo1, dtc3, vpo2, var;
        if (jcheck1.isSelected()) {
            pn = "Oui";
        } else {
            pn = "Non";
        }
        if (jcheck2.isSelected()) {
            bc = "Oui";
        } else {
            bc = "Non";
        }
        if (Jcheck3.isSelected()) {
            dt = "Oui";
        } else {
            dt = "Non";
        }
        if (Jcheck4.isSelected()) {
            vpo = "Oui";
        } else {
            vpo = "Non";
        }
        if (Jcheck5.isSelected()) {
            vpi = "Oui";
        } else {
            vpi = "Non";
        }
        if (jcheck6.isSelected()) {
            vpo1 = "Oui";
        } else {
            vpo1 = "Non";
        }
        if (jCheck8.isSelected()) {
            dtc3 = "Oui";
        } else {
            dtc3 = "Non";
        }
        if (JCheck9.isSelected()) {
            vpo2 = "Oui";

        } else {
            vpo2 = "Non";
        }
        if (JCheck10.isSelected()) {
            var = "Oui";
        } else {
            var = "Non";
        }

        //en.chargementCombo( "identite", "nom",code_pers);
        int id = en.Chargerid(code_pers,"v_entete", "code");
        en.Anamenese(ida, id, bc, dtc3, pn, vpo, vpi, vpo1, dtc3, vpo2, var, dat1, dat2, dat3, dat4, dat5, dat6, dat7, dat8, dat9, jtxt10, jtxt10, jtxt10, jtxt10, jtxt10, jtxt10, jtxt10, jtxt10, jtxt10, mois2, mois12, mois3, mois9, mois6, mois24, antecedent, environ, complement, motif, histoire, suivie, circonstance, alimentation,Home.admin1);
//        en.Anamenese(ida,id, bc, dt, pn, vpo, vpi, vpo1, dtc3, vpo2, var,
//            dat1,
//            jtxtLot1,
//            dat2, jtxtlot2,
//            dat3, jtxtlot3, dat4, histoire, dat5, dat8, dat7, jtxtlot7,
//            dat6, dat9, jtxtlot8, jtxtlot9, jtxt10, jtxtlot10, mois2, mois3, mois6, mois9, mois24, mois12,
//            antecedent, environ, complement,motif,histoire,suivie,
//            circonstance,alimentation);
        
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        //en.Changer(jLabel26);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
       // en.ExitChanger(jLabel26);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseExited

    private void code_persMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_code_persMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_code_persMouseClicked

    private void dat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dat9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dat9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCheck10;
    private javax.swing.JCheckBox JCheck9;
    private javax.swing.JCheckBox Jcheck3;
    private javax.swing.JCheckBox Jcheck4;
    private javax.swing.JCheckBox Jcheck5;
    private javax.swing.JTextField alimentation;
    private javax.swing.JTextArea antecedent;
    private javax.swing.JTextField circonstance;
    private javax.swing.JComboBox<String> code_pers;
    private javax.swing.JTextArea complement;
    private javax.swing.JTextField dat1;
    private javax.swing.JTextField dat2;
    private javax.swing.JTextField dat3;
    private javax.swing.JTextField dat4;
    private javax.swing.JTextField dat5;
    private javax.swing.JTextField dat6;
    private javax.swing.JTextField dat7;
    private javax.swing.JTextField dat8;
    private javax.swing.JTextField dat9;
    private javax.swing.JTextArea environ;
    private javax.swing.JTextField histoire;
    private javax.swing.JLabel ida;
    private javax.swing.JCheckBox jCheck8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox jcheck1;
    private javax.swing.JCheckBox jcheck2;
    private javax.swing.JCheckBox jcheck6;
    private javax.swing.JTextField jtxt10;
    private javax.swing.JTextField jtxtLot1;
    private javax.swing.JTextField jtxtlot10;
    private javax.swing.JTextField jtxtlot2;
    private javax.swing.JTextField jtxtlot3;
    private javax.swing.JTextField jtxtlot5;
    private javax.swing.JTextField jtxtlot7;
    private javax.swing.JTextField jtxtlot8;
    private javax.swing.JTextField jtxtlot9;
    private javax.swing.JTextField mois12;
    private javax.swing.JTextField mois2;
    private javax.swing.JTextField mois24;
    private javax.swing.JTextField mois3;
    private javax.swing.JTextField mois6;
    private javax.swing.JTextField mois9;
    private javax.swing.JTextField motif;
    private javax.swing.JTextField suivie;
    // End of variables declaration//GEN-END:variables
}
