/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.MenuFacturation;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author BIENFAIT
 */
public class Facturation extends javax.swing.JPanel {

    /**
     * Creates new form Facturation
     */
    Syncronisation.Syncroniser sy = new Syncronisation.Syncroniser();
//    double p2 = 0.0;

    public Facturation() {
        initComponents();
        //jPanel1.setBackground(new Color(192, 192, 255));
        jPanel2.setBackground(new Color(54, 175, 231));
        //agent.setText(Home.admin1.getText());
//        sy.ChargerCo(NomPatient,"en_tete_consultation", "patient", "ID");
        sy.chargementdetail(NomPatient);
        sy.ChargermentTable(TABLE_RESULT, "ServiceFinance", "IDF");
        sy.ChargermentTable(jTable1, "Factur", "id");
        id_fact.setVisible(false);
        exam18.setVisible(false);
        PRIX8.setVisible(false);
        exit5.setVisible(false);
        jLabel26.setVisible(false);
        jSeparator8.setVisible(false);
        id_pat.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        id_pat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NomPatient = new javax.swing.JComboBox();
        LISTEexamen = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        exam2 = new javax.swing.JLabel();
        exam1 = new javax.swing.JLabel();
        exam3 = new javax.swing.JLabel();
        exam7 = new javax.swing.JLabel();
        exam17 = new javax.swing.JLabel();
        exam18 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        exit4 = new javax.swing.JLabel();
        exit5 = new javax.swing.JLabel();
        exit6 = new javax.swing.JLabel();
        exit7 = new javax.swing.JLabel();
        exam4 = new javax.swing.JLabel();
        exam6 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        PRIX1 = new javax.swing.JLabel();
        PRIX2 = new javax.swing.JLabel();
        PRIX3 = new javax.swing.JLabel();
        PRIX4 = new javax.swing.JLabel();
        PRIX5 = new javax.swing.JLabel();
        PRIX6 = new javax.swing.JLabel();
        PRIX7 = new javax.swing.JLabel();
        exam5 = new javax.swing.JLabel();
        exit8 = new javax.swing.JLabel();
        PRIX8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLE_RESULT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        date_fac = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        id_fact = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_pat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        id_pat.setForeground(new java.awt.Color(0, 0, 153));
        id_pat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(id_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 24));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enregistrer");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setFocusable(false);
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 110, 30));

        NomPatient.setEditable(true);
        NomPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 153))); // NOI18N
        NomPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomPatientMouseClicked(evt);
            }
        });
        NomPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPatientActionPerformed(evt);
            }
        });
        jPanel2.add(NomPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 40));

        LISTEexamen.setBackground(new java.awt.Color(255, 255, 255));
        LISTEexamen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libelé                                                                      Prix ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 0, 153))); // NOI18N
        LISTEexamen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("2");
        LISTEexamen.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 22));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setText("1");
        LISTEexamen.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 22));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel22.setText("4");
        LISTEexamen.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setText("3");
        LISTEexamen.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 22));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel24.setText("6");
        LISTEexamen.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 15, 22));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel25.setText("5");
        LISTEexamen.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 22));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel26.setText("8");
        LISTEexamen.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 10, 22));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel27.setText("7");
        LISTEexamen.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 10, 22));

        exam2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 22));

        exam1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 22));

        exam3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 20));

        exam7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 402, 16, 22));

        exam17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 22));

        exam18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 22));

        exit2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 0, 51));
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        exit3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 0, 51));
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        exit4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit4.setForeground(new java.awt.Color(255, 0, 51));
        exit4.setText("X");
        exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit4MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        exit5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit5.setForeground(new java.awt.Color(255, 0, 51));
        exit5.setText("X");
        exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit5MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        exit6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit6.setForeground(new java.awt.Color(255, 0, 51));
        exit6.setText("X");
        exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit6MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        exit7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit7.setForeground(new java.awt.Color(255, 0, 51));
        exit7.setText("X");
        exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit7MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        exam4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 20));

        exam6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 22));

        exit1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 0, 51));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));
        LISTEexamen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 340, -1));
        LISTEexamen.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 340, -1));
        LISTEexamen.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, -1));
        LISTEexamen.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 350, 10));
        LISTEexamen.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 350, 10));
        LISTEexamen.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, -1));
        LISTEexamen.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 350, 10));
        LISTEexamen.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 350, 10));
        LISTEexamen.add(PRIX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 40, 22));
        LISTEexamen.add(PRIX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 40, 21));
        LISTEexamen.add(PRIX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 18));
        LISTEexamen.add(PRIX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 40, 18));
        LISTEexamen.add(PRIX5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 40, 20));
        LISTEexamen.add(PRIX6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, 18));
        LISTEexamen.add(PRIX7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 40, 20));

        exam5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LISTEexamen.add(exam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 20));

        exit8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit8.setForeground(new java.awt.Color(255, 0, 51));
        exit8.setText("X");
        exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit8MouseClicked(evt);
            }
        });
        LISTEexamen.add(exit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 10, 30));
        LISTEexamen.add(PRIX8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 40, 19));

        jPanel2.add(LISTEexamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 410, 270));

        TABLE_RESULT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TABLE_RESULT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_RESULTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TABLE_RESULT);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 460, 240));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter au Menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, 30));

        date_fac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date d'operation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 153))); // NOI18N
        date_fac.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(date_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 230, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("TOTAL:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 50, 30));

        id_fact.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        id_fact.setForeground(new java.awt.Color(0, 0, 153));
        id_fact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(id_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 24));
        jPanel2.add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Imprimer");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1040, 130));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
//
        if (((JTextField) date_fac.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez inserer la date svp !!");
        } else {
            int idf = sy.Chargerid(NomPatient, "v_entete", "code");
            sy.SaveFacturation(id_fact, idf, exam1, PRIX1, exam2, PRIX2, exam3, PRIX3, exam4, PRIX4, exam5, PRIX5, exam6, PRIX6, exam7, PRIX7, date_fac);
            sy.ChargermentTable(jTable1, "Factur", "id");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        sy.Changer(jLabel8);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        sy.ExitChanger(jLabel8);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void NomPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomPatientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NomPatientMouseClicked

    private void NomPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPatientActionPerformed
        //        en.Affichage(idagent, "identite", "id",nom, nomPere, sexe);
    }//GEN-LAST:event_NomPatientActionPerformed

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        exam2.setText("");
        PRIX2.setText("");
        exit2.setVisible(false);

    }//GEN-LAST:event_exit2MouseClicked

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        exam3.setText("");
        PRIX3.setText("");
        exit3.setVisible(false);
       
    }//GEN-LAST:event_exit3MouseClicked

    private void exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit4MouseClicked
        exam4.setText("");
        PRIX4.setText("");
        exit4.setVisible(false);
    }//GEN-LAST:event_exit4MouseClicked

    private void exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit5MouseClicked
        exam5.setText("");
        PRIX5.setText("");exit5.setVisible(false);
       
    }//GEN-LAST:event_exit5MouseClicked

    private void exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit6MouseClicked
        exam6.setText("");
        PRIX6.setText("");exit6.setVisible(false);
        
    }//GEN-LAST:event_exit6MouseClicked

    private void exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit7MouseClicked
        exam17.setText("");
        PRIX7.setText("");
        exit7.setVisible(false);
     
    }//GEN-LAST:event_exit7MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        exam1.setText("");
        PRIX1.setText("");
        exit1.setVisible(false);
    }//GEN-LAST:event_exit1MouseClicked

    private void exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit8MouseClicked
        exam5.setText("");
        PRIX5.setText("");
        exit8.setVisible(false);
    }//GEN-LAST:event_exit8MouseClicked

    private void TABLE_RESULTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_RESULTMouseClicked

        if (exam1.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam1, PRIX1);
            exit1.setVisible(true);
            } else if (!exam1.getText().equals("") && exam2.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam2, PRIX2);
            exit2.setVisible(true);
           } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && exam3.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam3, PRIX3);
            exit3.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && !exam3.getText().equals("") && exam4.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam4, PRIX4);
            exit4.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && !exam3.getText().equals("") && !exam4.getText().equals("") && exam5.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam5, PRIX5);
            exit5.setVisible(true);
           
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
                && !exam3.getText().equals("") && !exam4.getText().equals("") && !exam5.getText().equals("") && exam6.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam6, PRIX6);
            exit6.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
                && !exam3.getText().equals("") && !exam4.getText().equals("") && !exam5.getText().equals("") && !exam6.getText().equals("") && exam17.getText().equals("")) {
            sy.deplacerPrixLibele(TABLE_RESULT, exam17, PRIX7);
            exit7.setVisible(true);
        }
        
//        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
//                && !exam3.getText().equals("") && !exam4.getText().equals("") && !exam5.getText().equals("")
//                && !exam6.getText().equals("") && !exam17.getText().equals("") && exam18.getText().equals("")) {
//            sy.deplacerPrixLibele(TABLE_RESULT, exam18, PRIX8);
//            calcul8.setText(PRIX8.getText());
//            mes8.setText(" fois");
//            nb8.setVisible(true);
//            exit8.setVisible(true);
//        }
    }//GEN-LAST:event_TABLE_RESULTMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new MenuFacturation().show();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        sy.Changer(jLabel1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        sy.ExitChanger(jLabel1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String c = "Facture",
                req = "select facture.id,nom+' '+POSTNOM+' '+PRENOM NOM_PATIENT,ex1,prix,ex2,pri2,ex3,pri3,ex4,prix4,ex5,prix5,ex6,prix6,ex7,prix7,TOTAL  from facture inner join IDENTITE\n" +
"on IDENTITE.id=FACTURE.ID_PATIENT where id='" + id_fact.getText() + "'";
        try {
            sy.EtatSortie(req, c);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        sy.Changer(jLabel4);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        sy.ExitChanger(jLabel4);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        sy.deplacerfacture(jTable1, id_fact, exam1, PRIX1, exam2, PRIX2, exam3, PRIX3, exam4, PRIX4, exam5, PRIX5, exam6, PRIX6, exam7, PRIX7, TOTAL, date_fac);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LISTEexamen;
    private javax.swing.JComboBox NomPatient;
    private javax.swing.JLabel PRIX1;
    private javax.swing.JLabel PRIX2;
    private javax.swing.JLabel PRIX3;
    private javax.swing.JLabel PRIX4;
    private javax.swing.JLabel PRIX5;
    private javax.swing.JLabel PRIX6;
    private javax.swing.JLabel PRIX7;
    private javax.swing.JLabel PRIX8;
    private javax.swing.JTable TABLE_RESULT;
    private javax.swing.JLabel TOTAL;
    private com.toedter.calendar.JDateChooser date_fac;
    private javax.swing.JLabel exam1;
    private javax.swing.JLabel exam17;
    private javax.swing.JLabel exam18;
    private javax.swing.JLabel exam2;
    private javax.swing.JLabel exam3;
    private javax.swing.JLabel exam4;
    private javax.swing.JLabel exam5;
    private javax.swing.JLabel exam6;
    private javax.swing.JLabel exam7;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel exit4;
    private javax.swing.JLabel exit5;
    private javax.swing.JLabel exit6;
    private javax.swing.JLabel exit7;
    private javax.swing.JLabel exit8;
    private javax.swing.JLabel id_fact;
    private javax.swing.JLabel id_pat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
