/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.Home;
import java.awt.Color;

/**
 *
 * @author Honore
 */
public class Internement extends javax.swing.JPanel {

    /**
     * Creates new form Internement
     */
      Syncronisation.Syncroniser t = new Syncronisation.Syncroniser();

    public Internement() {
        initComponents();
         jPanel2.setBackground(new Color(54, 175, 231));
            // t.ChargerCo(perso, "identite", "NOM","ID");
             t.chargementdetail(perso);
        t.ChargermentTable(table_suivie, "[vSUIVIE]", "id");
        //agent.setText(Home.admin1.getText());
        jLabel2.setVisible(false);
        ordre.setVisible(false);
        RECHERCHER.setVisible(true);
          jPanel2.setBackground(new Color(54, 175, 231));
         LISTEexamen.setBackground(new Color(54, 175, 231));
          RECHERCHER.setBackground(new Color(54, 175, 231));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        id_inter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_suivie = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TABLE_RESULT = new javax.swing.JTable();
        paraclinique = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LISTEexamen = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        exam2 = new javax.swing.JLabel();
        exam1 = new javax.swing.JLabel();
        exam5 = new javax.swing.JLabel();
        exam3 = new javax.swing.JLabel();
        exam4 = new javax.swing.JLabel();
        exam7 = new javax.swing.JLabel();
        exam17 = new javax.swing.JLabel();
        exam18 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        exit4 = new javax.swing.JLabel();
        exit5 = new javax.swing.JLabel();
        exit6 = new javax.swing.JLabel();
        exit7 = new javax.swing.JLabel();
        exit8 = new javax.swing.JLabel();
        exam14 = new javax.swing.JLabel();
        exam16 = new javax.swing.JLabel();
        exam15 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObserva = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        traitement = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idp = new javax.swing.JLabel();
        Id_traitement = new javax.swing.JLabel();
        perso = new javax.swing.JComboBox<>();
        ordre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RECHERCHER = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Internement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_inter.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(id_inter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 220, 30));

        table_suivie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_suivie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_suivieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_suivie);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 850, 113));

        TABLE_RESULT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TABLE_RESULT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_RESULTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TABLE_RESULT);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 390, 107));

        paraclinique.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HEMATOLOGIE", "PARASITOLOGIE", "UROLOGIE", "LCR", "SERO IMMUNOLOGIE", "BIOCHIMIE", "AUTRES" }));
        paraclinique.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paraclinique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paracliniqueMouseClicked(evt);
            }
        });
        paraclinique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paracliniqueActionPerformed(evt);
            }
        });
        jPanel2.add(paraclinique, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 390, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Enregistrer");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 150, 30));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Modifier");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 110, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Imprimer");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 130, 30));

        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 270, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recherche");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 68, -1));

        LISTEexamen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examens demandés", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("2");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setText("1");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel22.setText("4");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel23.setText("3");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel24.setText("6");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel25.setText("5");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel26.setText("8");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel27.setText("7");

        exam2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exit2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 0, 51));
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        exit3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 0, 51));
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
        });

        exit4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit4.setForeground(new java.awt.Color(255, 0, 51));
        exit4.setText("X");
        exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit4MouseClicked(evt);
            }
        });

        exit5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit5.setForeground(new java.awt.Color(255, 0, 51));
        exit5.setText("X");
        exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit5MouseClicked(evt);
            }
        });

        exit6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit6.setForeground(new java.awt.Color(255, 0, 51));
        exit6.setText("X");
        exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit6MouseClicked(evt);
            }
        });

        exit7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit7.setForeground(new java.awt.Color(255, 0, 51));
        exit7.setText("X");
        exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit7MouseClicked(evt);
            }
        });

        exit8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit8.setForeground(new java.awt.Color(255, 0, 51));
        exit8.setText("X");
        exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit8MouseClicked(evt);
            }
        });

        exam14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exam15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        exit1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 0, 51));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LISTEexamenLayout = new javax.swing.GroupLayout(LISTEexamen);
        LISTEexamen.setLayout(LISTEexamenLayout);
        LISTEexamenLayout.setHorizontalGroup(
            LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LISTEexamenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(LISTEexamenLayout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(exam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(LISTEexamenLayout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(LISTEexamenLayout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exam3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LISTEexamenLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(exam15, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exam14, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exam16, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(LISTEexamenLayout.createSequentialGroup()
                            .addGap(412, 412, 412)
                            .addComponent(exam4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(exam7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LISTEexamenLayout.createSequentialGroup()
                            .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LISTEexamenLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(exam17, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LISTEexamenLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exam18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exam5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exit1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LISTEexamenLayout.setVerticalGroup(
            LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LISTEexamenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exam1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LISTEexamenLayout.createSequentialGroup()
                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LISTEexamenLayout.createSequentialGroup()
                                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exam2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exam3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(exit3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(exam14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(exit4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LISTEexamenLayout.createSequentialGroup()
                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LISTEexamenLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(exam4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exam15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LISTEexamenLayout.createSequentialGroup()
                                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exit6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LISTEexamenLayout.createSequentialGroup()
                                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(exit7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(LISTEexamenLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(LISTEexamenLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(LISTEexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(exit8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(exam18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(exam17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exam5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(exam7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(LISTEexamenLayout.createSequentialGroup()
                                .addComponent(exam16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(LISTEexamenLayout.createSequentialGroup()
                        .addComponent(exit5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2.add(LISTEexamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 308));

        txtObserva.setColumns(20);
        txtObserva.setRows(5);
        txtObserva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(txtObserva);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 93, 271, 110));

        traitement.setColumns(20);
        traitement.setRows(5);
        traitement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(traitement);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Traitement");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 91, 26));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° d'ordre :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 26));

        idp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 20));

        Id_traitement.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Id_traitement.setForeground(new java.awt.Color(255, 255, 255));
        Id_traitement.setText("Nom");
        jPanel2.add(Id_traitement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 17));

        perso.setEditable(true);
        perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persoActionPerformed(evt);
            }
        });
        jPanel2.add(perso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 270, -1));

        ordre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordreActionPerformed(evt);
            }
        });
        ordre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ordreKeyReleased(evt);
            }
        });
        jPanel2.add(ordre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Observation du medecin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 26));

        RECHERCHER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RECHERCHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECHERCHERActionPerformed(evt);
            }
        });
        RECHERCHER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RECHERCHERKeyReleased(evt);
            }
        });
        jPanel2.add(RECHERCHER, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void table_suivieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_suivieMouseClicked
        t.deplacerSuivi(table_suivie, idp);
    }//GEN-LAST:event_table_suivieMouseClicked

    private void TABLE_RESULTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_RESULTMouseClicked
        if (exam1.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam1);
            exit1.setVisible(true);
        } else if (!exam1.getText().equals("") && exam2.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam2);
            exit2.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && exam3.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam3);
            exit3.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && !exam3.getText().equals("") && exam14.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam14);
            exit4.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("") && !exam3.getText().equals("") && !exam14.getText().equals("") && exam15.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam15);
            exit5.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
            && !exam3.getText().equals("") && !exam14.getText().equals("") && !exam15.getText().equals("") && exam16.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam16);
            exit6.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
            && !exam3.getText().equals("") && !exam14.getText().equals("") && !exam15.getText().equals("") && !exam16.getText().equals("") && exam17.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam17);
            exit7.setVisible(true);
        } else if (!exam1.getText().equals("") && !exam2.getText().equals("")
            && !exam3.getText().equals("") && !exam14.getText().equals("") && !exam15.getText().equals("")
            && !exam16.getText().equals("") && !exam17.getText().equals("") && exam18.getText().equals("")) {
            t.deplacerEx1(TABLE_RESULT, exam18);
            exit8.setVisible(true);
        }
    }//GEN-LAST:event_TABLE_RESULTMouseClicked

    private void paracliniqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paracliniqueMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_paracliniqueMouseClicked

    private void paracliniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paracliniqueActionPerformed
        if (paraclinique.getSelectedItem().equals("HEMATOLOGIE")) {
            t.ChargermentTable(TABLE_RESULT, "HEMATOLOGIE", "ID");
        } else if (paraclinique.getSelectedItem().equals("PARASITOLOGIE")) {
            t.ChargermentTable(TABLE_RESULT, "PARASITOLOGIE", "id");
        } else if (paraclinique.getSelectedItem().equals("UROLOGIE")) {
            t.ChargermentTable(TABLE_RESULT, "UROLOGIE", "ID");
        } else if (paraclinique.getSelectedItem().equals("LCR")) {
            t.ChargermentTable(TABLE_RESULT, "LCR", "ID");
        } else if (paraclinique.getSelectedItem().equals("SERO_IMMUNOLOGIE")) {
            t.ChargermentTable(TABLE_RESULT, "SERO_IMMUNOLOGIE","ID");
        } else if (paraclinique.getSelectedItem().equals("BIOCHIMIE")) {
            t.ChargermentTable(TABLE_RESULT, "BIOCHIMIE", "ID");
        } else if (paraclinique.getSelectedItem().equals("AUTRES")) {

            t.ChargermentTable(TABLE_RESULT, "AUTRES", "ID");
        }
    }//GEN-LAST:event_paracliniqueActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        int id = t.Chargerid(perso, "identite", "id");
        String nom = t.ChargerNomAgent(perso, "identite", "NOM");
        t.enregistrementSuiVi(id, nom, txtObserva,traitement, Home.admin1, exam1, exam2, exam3, exam14, exam15, exam16, exam17, exam18,ordre);
        t.ChargermentTable(table_suivie, "vSUIVIE", "id");
       txtObserva.setText("");
     traitement.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        t.Changer(jLabel16);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        t.ExitChanger(jLabel16);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        t.Changer(jLabel17);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        t.ExitChanger(jLabel17);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
       // t.FicheSuivie(idp);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        t.Changer(jLabel18);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        t.ExitChanger(jLabel18);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseExited

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        exam2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseClicked

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        exam3.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_exit3MouseClicked

    private void exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit4MouseClicked
        exam14.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_exit4MouseClicked

    private void exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit5MouseClicked
        exam15.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_exit5MouseClicked

    private void exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit6MouseClicked
        exam16.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_exit6MouseClicked

    private void exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit7MouseClicked
        exam17.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_exit7MouseClicked

    private void exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit8MouseClicked
        exam18.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_exit8MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        exam1.setText("");
    }//GEN-LAST:event_exit1MouseClicked

    private void persoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persoActionPerformed

    private void ordreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordreActionPerformed

    private void ordreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ordreKeyReleased
        t.Recherchecombo(perso, "identite", "NOM", ordre);        // TODO add your handling code here:
    }//GEN-LAST:event_ordreKeyReleased

    private void RECHERCHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECHERCHERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RECHERCHERActionPerformed

    private void RECHERCHERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RECHERCHERKeyReleased
        t.Recherchecombo(perso, "identite", "NOM", RECHERCHER);

    }//GEN-LAST:event_RECHERCHERKeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        t.RechercherSuivie(table_suivie, "vSUIVIE", "id", jTextField2);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id_traitement;
    private javax.swing.JPanel LISTEexamen;
    private javax.swing.JTextField RECHERCHER;
    private javax.swing.JTable TABLE_RESULT;
    private javax.swing.JLabel exam1;
    private javax.swing.JLabel exam14;
    private javax.swing.JLabel exam15;
    private javax.swing.JLabel exam16;
    private javax.swing.JLabel exam17;
    private javax.swing.JLabel exam18;
    private javax.swing.JLabel exam2;
    private javax.swing.JLabel exam3;
    private javax.swing.JLabel exam4;
    private javax.swing.JLabel exam5;
    private javax.swing.JLabel exam7;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel exit4;
    private javax.swing.JLabel exit5;
    private javax.swing.JLabel exit6;
    private javax.swing.JLabel exit7;
    private javax.swing.JLabel exit8;
    private javax.swing.JLabel id_inter;
    private javax.swing.JLabel idp;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField ordre;
    private javax.swing.JComboBox paraclinique;
    private javax.swing.JComboBox<String> perso;
    private javax.swing.JTable table_suivie;
    private javax.swing.JTextArea traitement;
    private javax.swing.JTextArea txtObserva;
    // End of variables declaration//GEN-END:variables
}
