/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.Home;
import Syncronisation.Syncroniser;
import java.awt.Color;

/**
 *
 * @author Honore
 */
public class Laboratoire extends javax.swing.JPanel {

    /**
     * Creates new form Laboratoire
     */
    Syncronisation.Syncroniser sy = new Syncroniser();
    public Laboratoire() {
        initComponents();
        jPanel2.setBackground(new Color(54, 175, 231));
        jPanel7.setBackground(new Color(54, 175, 231));
        sy.affichage(result, "select * from vresultat");
        sy.TableCharg(labo," * from Paraclin");
         sy.chargementdetail(code_pers);
         nom.setVisible(false);
         id.setVisible(false);
         id1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nom = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        exam2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        exam35 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        exam36 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        exam37 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        exam38 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        exam39 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        exam40 = new javax.swing.JLabel();
        exam1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labo = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();
        id = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        demandeur = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jXSearchField2 = new org.jdesktop.swingx.JXSearchField();
        code_pers = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Resultat du laboratoire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1. HEMATOLOGIE\nHémogramme\nGB : ........(5000 – 10.000/mm3)\nFL : \nHb : …..... Hct : \nTaux de réticulocytes : …. (0,4 – 2,5%)\nVitesse de sédimentation: ... (3 – 8mm/h)\nTemps de saignement : …  (0 – 7min)\nTemps de coagulation : ... (5 – 12min)\nTest d’Emmel: \n----------------------------------------\n2. {PARASITOLOGIE.}\nGoutte Epaisse : … TDR: \nGoutte Fraîche : \nSelles direct : \n----------------------------------------\n3. UROLOGIE\nGlucoserie : \nProtéinurie : \nSédiment Urinaire : \nGRAM : \nFrottis Vaginal : \n----------------------------------------\n4. LCR : \nCytologie : … ˂ 3 à 5 cellules/uL\nProteinorrachie : … (0,30 à 0,50g/L)\nGlucorrachie : \nSédiment Urinaire : \nGRAM : \nFrottis Vaginal : \n----------------------------------------\n5.  SERO IMMUNOLOGIE\nCRP: .... (˂ 6mg/l)\nPro calcitonine: .... (˂ 0,5ng/ml)\nH. pylori: \nGroupe Sanguin: .... Rh: \nWIDAL: TO: ... TH: \nHbsAg: \nASLO: \nHépatite C: \nVIH : \nTPHA : \n----------------------------------------\n6.  BIOCHIMIE\nGlycémie : .... (60 – 110mg/dl)\nUrée : .... (15 – 45mg/dl)\n Créatinine .... (0,6- 1,1mg/dl)\nSGOT/ ASAT: .... (5-40UI/L)\nSGPT/ ALAT : .... ( 5-45UI/L)\nBilirubine Direct : .... ˂0,25mg/dl\nBilirubine Total : ....˂ 1,10mg/dl\nBilirubine Indirect:    \nAcide Urique : .... (4 - 6,6mg/dl)\nHbA1c : .... (4 – 6,5%)\n----------------------------------------\n7.  IONOGRAMME\nPotassium : .... (3,5 – 4,5mEq/l)\nMagnésium : .... (1,6 – 2,5mg/dl)\nCalcium: .... (8, 4 – 10,2mg/dl)\nSodium .... (137 – 143mEq/l)\nChlore .... (100 – 110mEq/l)\n8. AUTRES : ");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrer les informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 500, 360));
        jPanel2.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 130, 22));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examens demandés", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel48.setText("1");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 18, -1));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel49.setText("2");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 16, 18, -1));

        exam2.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 16, 136, 19));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel50.setText("3");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 16, 18, -1));

        exam35.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam35, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 16, 100, 19));

        jLabel51.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel51.setText("4");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, 18, -1));

        exam36.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam36, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 46, 136, 19));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel52.setText("5");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 46, 18, -1));

        exam37.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 41, 136, 19));

        jLabel53.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel53.setText("6");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 41, 18, -1));

        exam38.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 100, 19));

        jLabel54.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel54.setText("7");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, 18, -1));

        exam39.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam39, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 71, 136, 19));

        jLabel55.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel55.setText("8");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 66, 18, -1));

        exam40.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 66, 136, 19));

        exam1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel7.add(exam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 16, 136, 19));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 500, 110));

        labo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        labo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laboMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(labo);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1030, 120));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Actualiser");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 180, 40));

        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(result);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 480, 150));
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 53, 22));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Demandeur");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 78, 30));

        demandeur.setForeground(new java.awt.Color(153, 153, 0));
        jPanel2.add(demandeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 74, 120, 22));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Supprimer");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 170, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Valider");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 180, 40));
        jPanel2.add(jXSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 290, 30));
        jPanel2.add(jXSearchField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 250, 30));

        code_pers.setEditable(true);
        jPanel2.add(code_pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Personne");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 70, 30));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Demandeur");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 90, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Imprimer");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 180, 40));
        jPanel2.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 53, 22));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void laboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboMouseClicked
       sy.deplacerlabo(labo, nom, demandeur, exam1, exam2);
    }//GEN-LAST:event_laboMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        String act="1. HEMATOLOGIE\n" +
"Hémogramme\n" +
"GB : ........(5000 – 10.000/mm3)\n" +
"FL : \n" +
"Hb : …..... Hct : \n" +
"Taux de réticulocytes : …. (0,4 – 2,5%)\n" +
"Vitesse de sédimentation: ... (3 – 8mm/h)\n" +
"Temps de saignement : …  (0 – 7min)\n" +
"Temps de coagulation : ... (5 – 12min)\n" +
"Test d’Emmel: \n" +
"----------------------------------------\n" +
"2. {PARASITOLOGIE.}\n" +
"Goutte Epaisse : … TDR: \n" +
"Goutte Fraîche : \n" +
"Selles direct : \n" +
"----------------------------------------\n" +
"3. UROLOGIE\n" +
"Glucoserie : \n" +
"Protéinurie : \n" +
"Sédiment Urinaire : \n" +
"GRAM : \n" +
"Frottis Vaginal : \n" +
"----------------------------------------\n" +
"4. LCR : \n" +
"Cytologie : … ˂ 3 à 5 cellules/uL\n" +
"Proteinorrachie : … (0,30 à 0,50g/L)\n" +
"Glucorrachie : \n" +
"Sédiment Urinaire : \n" +
"GRAM : \n" +
"Frottis Vaginal : \n" +
"----------------------------------------\n" +
"5.  SERO IMMUNOLOGIE\n" +
"CRP: .... (˂ 6mg/l)\n" +
"Pro calcitonine: .... (˂ 0,5ng/ml)\n" +
"H. pylori: \n" +
"Groupe Sanguin: .... Rh: \n" +
"WIDAL: TO: ... TH: \n" +
"HbsAg: \n" +
"ASLO: \n" +
"Hépatite C: \n" +
"VIH : \n" +
"TPHA : \n" +
"----------------------------------------\n" +
"6.  BIOCHIMIE\n" +
"Glycémie : .... (60 – 110mg/dl)\n" +
"Urée : .... (15 – 45mg/dl)\n" +
" Créatinine .... (0,6- 1,1mg/dl)\n" +
"SGOT/ ASAT: .... (5-40UI/L)\n" +
"SGPT/ ALAT : .... ( 5-45UI/L)\n" +
"Bilirubine Direct : .... ˂0,25mg/dl\n" +
"Bilirubine Total : ....˂ 1,10mg/dl\n" +
"Bilirubine Indirect:    \n" +
"Acide Urique : .... (4 - 6,6mg/dl)\n" +
"HbA1c : .... (4 – 6,5%)\n" +
"----------------------------------------\n" +
"7.  IONOGRAMME\n" +
"Potassium : .... (3,5 – 4,5mEq/l)\n" +
"Magnésium : .... (1,6 – 2,5mg/dl)\n" +
"Calcium: .... (8, 4 – 10,2mg/dl)\n" +
"Sodium .... (137 – 143mEq/l)\n" +
"Chlore .... (100 – 110mEq/l)\n" +
"8. AUTRES : ";
        jTextArea1.setText(act);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        //en.Changer(jLabel15);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        //en.ExitChanger(jLabel15);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseClicked
        //en.deplacerIdRes(TABLE_LABO, id, agent, jTextArea1);       // TODO add your handling code here:
    }//GEN-LAST:event_resultMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        //en.Suppression("paraclinique", "id", id);
        //en.ChargermentTable(TABLE_RESULT, "paraclinique", "id");
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        //en.Changer(jLabel20);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        //en.ExitChanger(jLabel20);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
         String idi= sy.chargernom(nom, "identite", "nom");
        sy.LaboResult(id, nom.getText(), Home.admin1, jTextArea1);
 sy.affichage(result, "select * from vresultat");
 jTextArea1.setText("");
//String idp = en.ChargerNomLabel(nom, "identite", "nom");
        //int id_pers = en.ChargeridLabel(nom, "identite", "ID");
        //en.saveLaboResult(id_pers, agent, jTextArea1, idp,agent);
//     en.ChargermentTable(TABLE_LABO, "result", "id");
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
       // en.Changer(jLabel16);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
//        en.ExitChanger(jLabel16);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
       String c="Labo",
               req="SELECT RESULTAT.ID, NOM as [NOM DU MALADE], RESULTAT.AGENT AS [NOM MEDECIN], RESULTAT AS [RESULTAT DU LABO] FROM RESULTAT inner join IDENTITE on IDENTITE.ID=resultat.ID_PERSONNE where vresultat.id='"+id.getText()+"'";
        try {
             sy.EtatSortie(req,c);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox code_pers;
    private javax.swing.JLabel demandeur;
    private javax.swing.JLabel exam1;
    private javax.swing.JLabel exam2;
    private javax.swing.JLabel exam35;
    private javax.swing.JLabel exam36;
    private javax.swing.JLabel exam37;
    private javax.swing.JLabel exam38;
    private javax.swing.JLabel exam39;
    private javax.swing.JLabel exam40;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXSearchField jXSearchField2;
    private javax.swing.JTable labo;
    private javax.swing.JLabel nom;
    private javax.swing.JTable result;
    // End of variables declaration//GEN-END:variables
}
