/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Syncronisation.Syncroniser;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Soft developpers
 */
public class Panier extends javax.swing.JPanel {

    /**
     * Creates new form Panier
     */
    Syncroniser sy = new Syncroniser();
    String c, req;

    public Panier() {
        initComponents();
        jPanel1.setBackground(new Color(54, 175, 231));
        jPanel2.setBackground(new Color(54, 175, 231));
        jPanel3.setBackground(new Color(54, 175, 231));
        jPanel4.setBackground(new Color(54, 175, 231));
        idach.setVisible(false);
        idpers.setVisible(false);
        idprod.setVisible(false);
        jLabel5.setVisible(false);
        tot_achat.setVisible(false);
        jLabel6.setVisible(false);
        jLabel11.setVisible(false);
        sy.affichage(panier, "select * from vente");
        sy.affichage(Rapport, "select * from [dbo].[RAPPORT_ACHAT]");
        sy.affichage(savePanier, "select * from [dbo].[TOTACH]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panier = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        idpers = new javax.swing.JLabel();
        idprod = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        print = new javax.swing.JLabel();
        idach = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        savePanier = new javax.swing.JTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        tot_achat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rapport = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mes commandes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(panier);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 520, 170));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TOTAL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 33));
        jPanel2.add(idpers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 21));
        jPanel2.add(idprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 21));

        jDateChooser3.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Date d'achat");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 20, 80, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enregistrer");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 20, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, 230));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        print.setForeground(new java.awt.Color(0, 0, 153));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Imprimer");
        print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        jPanel3.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 130, 30));
        jPanel3.add(idach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        savePanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        savePanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePanierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(savePanier);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 520, 260));
        jPanel3.add(jXSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 190, -1));

        tot_achat.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        tot_achat.setForeground(new java.awt.Color(255, 0, 0));
        tot_achat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot_achat.setText("TOTAL");
        jPanel3.add(tot_achat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 33));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("$");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 20, 33));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 520, 310));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rapport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Rapport);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 620, 510));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Imprimer");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setMaximumSize(new java.awt.Dimension(81, 18));
        jLabel4.setMinimumSize(new java.awt.Dimension(81, 18));
        jLabel4.setPreferredSize(new java.awt.Dimension(81, 20));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 100, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("$");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 28, 33));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("TOTAL");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 160, 33));

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel4.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 30));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 640, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panierMouseClicked
        //        en.deplacerPanier(panier, jLabel5);
        //        en.deplaceP1(panier, idprod, idpers);
        //        en.Somme(jLabel5);
        //        Rapport.setVisible(true);
        //        jLabel3.setVisible(true);
        sy.retourpanier(panier, idpers, idprod, "vente", "codevente", 6, 7);
        sy.totpanier(jLabel5, "total", "vente");
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
    }//GEN-LAST:event_panierMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (idpers.getText().isEmpty() || idprod.getText().isEmpty() || ((JTextField) jDateChooser3.getDateEditor().getUiComponent()).getText().isEmpty() || jLabel5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completez tout les champs svp !!");
        } else {
            sy.SaveTotal(idach, idprod, jLabel5, jDateChooser3, idpers);
            sy.affichage(savePanier, "select * from [dbo].[TOTACH]");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        c = "RecuPharmacie";
        req = "select V.CODEVENTE,v.quantite,pu,v.total,Date_operation,nom_produit,nom,[TOTACH].TOTAL from vente v inner join IDENTITE on IDENTITE.ID=v.code_personne inner join\n"
                + "PHARMACIE on PHARMACIE.ID=v.id inner join TOTACH on TOTACH.CODE_PATIENT=IDENTITE.id where TOTACH.ID='" + idach.getText() + "' ";

        if (idach.getText().isEmpty() || tot_achat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Impossible de faire l'impression");
        } else {
             try {
             sy.EtatSortie(req,c);
        } catch (Exception e) {
        }
            sy.Viderpanier();
        }
    }//GEN-LAST:event_printMouseClicked
    private void savePanierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePanierMouseClicked
        sy.retourpanier(savePanier, idach, tot_achat, "TOTACH", "id", 1, 2);
        tot_achat.setVisible(true);
        jLabel11.setVisible(true);
        //        print.setVisible(true);
    }//GEN-LAST:event_savePanierMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        c = "RapportVente";
        req = "select r.QUANTITE,r.[PRIX UNITAIRE],r.TOTAL as Tot,r.[DATE D'ACHAT],nom_produit,nom+' '+postnom+' '+prenom as patient from RAPPORT_ACHAT r \n"
                + "inner join PHARMACIE p on p.id=r.id_produit inner join IDENTITE on IDENTITE.ID=r.ID_PERSONNE where r.[DATE D'ACHAT] between '" + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText() + "'";
        if (((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner la date avant d'imprimer ");
        } else {
             try {
             sy.EtatSortie(req,c);
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        sy.Charger(Rapport, "select * from RAPPORT_ACHAT where [DATE D'ACHAT] between '" + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText() + "'");
        sy.SommeVente(jLabel8, jDateChooser1, jDateChooser2);
        //        jLabel4.setVisible(true);
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        sy.Charger(Rapport, "select * from RAPPORT_ACHAT where [DATE D'ACHAT] between '" + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + "' and '" + ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText() + "'");
        sy.SommeVente(jLabel8, jDateChooser1, jDateChooser2);
    }//GEN-LAST:event_jDateChooser1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Rapport;
    private javax.swing.JLabel idach;
    private javax.swing.JLabel idpers;
    private javax.swing.JLabel idprod;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private javax.swing.JTable panier;
    private javax.swing.JLabel print;
    private javax.swing.JTable savePanier;
    private javax.swing.JLabel tot_achat;
    // End of variables declaration//GEN-END:variables
}
