/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.AjoutExamen;
import Gui.Home;
import Syncronisation.Syncroniser;
import java.awt.Color;
//import javax.swing.JOptionPane;
//import org.springframework.mail.MailAuthenticationException;

/**
 *
 * @author honore
 */
public class Paraclinique extends javax.swing.JPanel {

    /**
     * Creates new form Paraclinique
     */
    Syncroniser sy = new Syncroniser();

    public Paraclinique() {
        initComponents();
//        jPanel7.setBackground(new Color(54, 175, 231));
        jPanel6.setBackground(new Color(54, 175, 231));
        jPanel4.setBackground(new Color(54, 175, 231));
        jPanel5.setBackground(new Color(54, 175, 231));
        jTable3.setBackground(new Color(54, 175, 231));
         sy.chargementdetail(jComboBox1);
//        sy.chargementCombo("identite", "nom", jComboBox1);
        id.setVisible(false);
        exit1.setVisible(false);
        exit2.setVisible(false);
        exit3.setVisible(false);
        exit4.setVisible(false);
        exit5.setVisible(false);
        exit6.setVisible(false);
        exit7.setVisible(false);
        exit8.setVisible(false);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
//        sy.affichage(jTable2, "select * from anamnese");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pphysique = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        exit4 = new javax.swing.JLabel();
        exit5 = new javax.swing.JLabel();
        exit6 = new javax.swing.JLabel();
        exit7 = new javax.swing.JLabel();
        exit8 = new javax.swing.JLabel();
        envoielabo = new javax.swing.JLabel();
        envoieimagerie = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        exa8 = new javax.swing.JLabel();
        exa1 = new javax.swing.JLabel();
        exa2 = new javax.swing.JLabel();
        exa3 = new javax.swing.JLabel();
        exa4 = new javax.swing.JLabel();
        exa5 = new javax.swing.JLabel();
        exa6 = new javax.swing.JLabel();
        exa7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pphysique.setBackground(new java.awt.Color(255, 255, 255));
        pphysique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)), "PARACLINIQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 10));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("A. HEMATOLOGIE");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("B. PARASITOLOGIE");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 40));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("C.UROLOGIE");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("D. LCR ");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 130, 40));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(" E. SEROIMMUNOLOGIE");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 140, 40));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("I.IONOGRAMME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 140, 40));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("F.BIOCHIMIE");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 140, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information sur Examen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 230));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Imagérie");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom de patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 240, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 520));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Etiquette", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setForeground(new java.awt.Color(0, 0, 255));
        l1.setText("1");
        jPanel6.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        l8.setForeground(new java.awt.Color(0, 0, 255));
        l8.setText("8");
        jPanel6.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 20, -1));

        l2.setForeground(new java.awt.Color(0, 0, 255));
        l2.setText("2");
        jPanel6.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 40, 20));

        l3.setForeground(new java.awt.Color(0, 0, 255));
        l3.setText("3");
        jPanel6.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 20, 30));

        l4.setForeground(new java.awt.Color(0, 0, 255));
        l4.setText("4");
        jPanel6.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 20, -1));

        l5.setForeground(new java.awt.Color(0, 0, 255));
        l5.setText("5");
        jPanel6.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 20, -1));

        l6.setForeground(new java.awt.Color(0, 0, 255));
        l6.setText("6");
        jPanel6.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 20, -1));

        l7.setForeground(new java.awt.Color(0, 0, 255));
        l7.setText("7");
        jPanel6.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 20, -1));

        exit1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 0, 51));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        jPanel6.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, 40));

        exit2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 0, 51));
        exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });
        jPanel6.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 40, 30));

        exit3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 0, 51));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
        });
        jPanel6.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 40, 30));

        exit4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit4.setForeground(new java.awt.Color(255, 0, 51));
        exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit4.setText("X");
        exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit4MouseClicked(evt);
            }
        });
        jPanel6.add(exit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 40, 30));

        exit5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit5.setForeground(new java.awt.Color(255, 0, 51));
        exit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit5.setText("X");
        exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit5MouseClicked(evt);
            }
        });
        jPanel6.add(exit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 40, 30));

        exit6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit6.setForeground(new java.awt.Color(255, 0, 51));
        exit6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit6.setText("X");
        exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit6MouseClicked(evt);
            }
        });
        jPanel6.add(exit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 40, 30));

        exit7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit7.setForeground(new java.awt.Color(255, 0, 51));
        exit7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit7.setText("X");
        exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit7MouseClicked(evt);
            }
        });
        jPanel6.add(exit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, 30));

        exit8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit8.setForeground(new java.awt.Color(255, 0, 51));
        exit8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit8.setText("X");
        exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit8MouseClicked(evt);
            }
        });
        jPanel6.add(exit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 40, 30));

        envoielabo.setBackground(new java.awt.Color(255, 255, 255));
        envoielabo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        envoielabo.setForeground(new java.awt.Color(255, 255, 255));
        envoielabo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        envoielabo.setText("Envoyer au labo");
        envoielabo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        envoielabo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                envoielaboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                envoielaboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                envoielaboMouseExited(evt);
            }
        });
        jPanel6.add(envoielabo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 40));

        envoieimagerie.setBackground(new java.awt.Color(255, 255, 255));
        envoieimagerie.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        envoieimagerie.setForeground(new java.awt.Color(255, 255, 255));
        envoieimagerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        envoieimagerie.setText("Envoyer à l'Imagerie");
        envoieimagerie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        envoieimagerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                envoieimagerieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                envoieimagerieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                envoieimagerieMouseExited(evt);
            }
        });
        jPanel6.add(envoieimagerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, 40));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Ajouter un examen");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel36MouseExited(evt);
            }
        });
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 180, 40));
        jPanel6.add(exa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 460, 30));
        jPanel6.add(exa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 460, 30));
        jPanel6.add(exa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 460, 30));
        jPanel6.add(exa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 460, 30));
        jPanel6.add(exa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 460, 30));
        jPanel6.add(exa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 460, 30));
        jPanel6.add(exa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 460, 30));
        jPanel6.add(exa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 460, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 620, 350));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("K. AUTRES  ");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 140, 40));

        pphysique.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1170, 590));

        add(pphysique, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1190, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        envoielabo.setVisible(false);
        envoieimagerie.setVisible(true);
        sy.affichage(jTable3, "select * from ExamenImagerie");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        sy.affichage(jTable3, "select * from HEMATOLOGIE");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        sy.affichage(jTable3, "select * from PARASITOLOGIE");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        sy.affichage(jTable3, "select * from urologie");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        sy.affichage(jTable3, "select * from lcr");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        sy.affichage(jTable3, "select * from SERO_IMMUNOLOGIE");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        sy.affichage(jTable3, "select * from IONOGRAMME");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        sy.affichage(jTable3, "select * from biochimie");
        envoieimagerie.setVisible(false);
        envoielabo.setVisible(true);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        exa1.setText("");
        exit1.setVisible(false);
        l1.setVisible(false);
    }//GEN-LAST:event_exit1MouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        exa2.setText("");
        exit2.setVisible(false);
        l2.setVisible(false);
    }//GEN-LAST:event_exit2MouseClicked

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        exa3.setText("");
        exit3.setVisible(false);
        l3.setVisible(false);
    }//GEN-LAST:event_exit3MouseClicked

    private void exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit4MouseClicked
        exa4.setText("");
        exit4.setVisible(false);
        l4.setVisible(false);
    }//GEN-LAST:event_exit4MouseClicked

    private void exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit5MouseClicked
        exa5.setText("");
        exit5.setVisible(false);
        l5.setVisible(false);
    }//GEN-LAST:event_exit5MouseClicked

    private void exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit6MouseClicked
        exa6.setText("");
        exit6.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_exit6MouseClicked

    private void exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit7MouseClicked
        exa7.setText("");
        exit7.setVisible(false);
        l7.setVisible(false);
    }//GEN-LAST:event_exit7MouseClicked

    private void exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit8MouseClicked
        exa8.setText("");
        exit8.setVisible(false);
        l8.setVisible(false);
    }//GEN-LAST:event_exit8MouseClicked

    private void envoielaboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoielaboMouseClicked
        int idr = sy.Chargerid(jComboBox1, "identite", "id");
        sy.paraclinique(id, Home.admin1, exa1, exa2, exa3, exa4, exa5, exa6, exa7, exa8, idr, "EXEC sp_paraclinique ?,?,?,?,?,?,?,?,?,?,?");
       
    }//GEN-LAST:event_envoielaboMouseClicked

    private void envoielaboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoielaboMouseEntered

    }//GEN-LAST:event_envoielaboMouseEntered

    private void envoielaboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoielaboMouseExited

    }//GEN-LAST:event_envoielaboMouseExited

    private void envoieimagerieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoieimagerieMouseClicked

        int idr = sy.Chargerid(jComboBox1, "identite", "id");
        sy.saveImagerie(id, idr, Home.admin1, exa1, exa2, exa3, exa4, exa5, exa6, exa7, exa8, "exec sp_imagerie ?,?,?,?,?,?,?,?,?,?,?");

    }//GEN-LAST:event_envoieimagerieMouseClicked

    private void envoieimagerieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoieimagerieMouseEntered
        //t.Changer(jLabel11);        // TODO add your handling code here:
    }//GEN-LAST:event_envoieimagerieMouseEntered

    private void envoieimagerieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_envoieimagerieMouseExited
        // t.ExitChanger(jLabel11);        // TODO add your handling code here:
    }//GEN-LAST:event_envoieimagerieMouseExited

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        new AjoutExamen(null, true).show();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseEntered
        // t.Changer(jLabel36);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseEntered

    private void jLabel36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseExited
        //t.ExitChanger(jLabel36);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseExited

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        sy.affichage(jTable3, "select * from autres");
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        sy.deplacermaladie(jTable3, exa1, exit1, exit2, exit3, exit4, exit5, exit6, exit7, exit8, exa2, exa3, exa4, exa5, exa6, exa7, exa8, l1, l2, l3, l4, l5, l6, l7, l8);
    }//GEN-LAST:event_jTable3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel envoieimagerie;
    private javax.swing.JLabel envoielabo;
    private javax.swing.JLabel exa1;
    private javax.swing.JLabel exa2;
    private javax.swing.JLabel exa3;
    private javax.swing.JLabel exa4;
    private javax.swing.JLabel exa5;
    private javax.swing.JLabel exa6;
    private javax.swing.JLabel exa7;
    private javax.swing.JLabel exa8;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel exit4;
    private javax.swing.JLabel exit5;
    private javax.swing.JLabel exit6;
    private javax.swing.JLabel exit7;
    private javax.swing.JLabel exit8;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    public static javax.swing.JPanel pphysique;
    // End of variables declaration//GEN-END:variables
}
