/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Gui.Home;
import Syncronisation.Syncroniser;
import java.awt.Color;

/**
 *
 * @author honore
 */
public class Physique extends javax.swing.JPanel {

    /**
     * Creates new form Physique
     */
    Syncroniser sy = new Syncroniser();
    
    public Physique() {
        initComponents();
        pphysique.setBackground(new Color(54, 175, 231));
        jPanel4.setBackground(new Color(54, 175, 231));
        jPanel2.setBackground(new Color(54, 175, 231));
        // agent.setBackground(new Color(54, 175, 231));
        sy.chargementdetail(jComboBox1);
        id.setVisible(false);
        sy.affichage(jTable1, "SELECT * FROM v_physique ORDER BY CODE DESC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pphysique = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ta = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        mensuration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        peau = new javax.swing.JTextField();
        aire = new javax.swing.JTextField();
        etat = new javax.swing.JTextField();
        sphere = new javax.swing.JTextField();
        temp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        fr = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        sa02 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        taille = new javax.swing.JTextField();
        thorax = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        pouls = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        abdomen = new javax.swing.JTextField();
        organe = new javax.swing.JTextField();
        apareil = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        examen = new javax.swing.JTextField();
        resumer = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        hypothese = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        rech = new org.jdesktop.swingx.JXSearchField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pphysique.setBackground(new java.awt.Color(255, 255, 255));
        pphysique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)), "PHYSIQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 280, 30));
        jPanel4.add(fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 280, 30));
        jPanel4.add(mensuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Fc");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Mensuration_poids");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Ta");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));

        jLabel21.setForeground(new java.awt.Color(51, 0, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Modifié");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 40));

        jLabel22.setForeground(new java.awt.Color(51, 0, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Enregistré");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 40));

        jLabel23.setForeground(new java.awt.Color(51, 0, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Supprimé");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 170, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("Sphere oral");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 80, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 153));
        jLabel25.setText("Aires gangl");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 153));
        jLabel26.setText("Paeu");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 80, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 153));
        jLabel27.setText("Etat général");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 153));
        jLabel28.setText("Pouls");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 80, 30));
        jPanel4.add(peau, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 310, 30));
        jPanel4.add(aire, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 310, 30));
        jPanel4.add(etat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 310, 30));
        jPanel4.add(sphere, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 310, 30));
        jPanel4.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 280, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 153));
        jLabel29.setText("Temp");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 10));
        jPanel4.add(fr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 280, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 153));
        jLabel30.setText("Fr");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));
        jPanel4.add(sa02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 280, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("Sa02");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("Taille");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));
        jPanel4.add(taille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 30));
        jPanel4.add(thorax, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 310, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 153));
        jLabel33.setText("Thorax");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 80, 30));
        jPanel4.add(pouls, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 310, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 153));
        jLabel34.setText("Abdomen");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 153));
        jLabel35.setText("Organe Gen");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 90, 30));
        jPanel4.add(abdomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 310, 30));
        jPanel4.add(organe, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 250, 30));
        jPanel4.add(apareil, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 250, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 153));
        jLabel36.setText("Appareil loco");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 90, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 153));
        jLabel37.setText("Examen neuro");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 90, 30));
        jPanel4.add(examen, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 250, 30));
        jPanel4.add(resumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 250, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 153));
        jLabel38.setText("Resume_sydro");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 90, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 153));
        jLabel39.setText("Hypothèse");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 90, 30));
        jPanel4.add(hypothese, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 250, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 153));
        jLabel40.setText("Nom patient");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 90, 30));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 250, 30));

        jLabel41.setForeground(new java.awt.Color(51, 0, 204));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Imprimer");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 170, 40));

        rech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechKeyReleased(evt);
            }
        });
        jPanel4.add(rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 252, 310, 30));

        pphysique.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1150, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information sur physique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1100, 230));

        pphysique.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1150, 260));

        add(pphysique, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        int idr = sy.Chargerid(jComboBox1, "identite", "id");
        sy.insertionPhysique(id, idr, Home.admin1, temp, fc, fr, sa02, mensuration, taille, ta, pouls, etat, peau, aire, sphere, thorax, abdomen, organe, apareil, examen, resumer, hypothese, "exec sp_physique ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", "Modification effectuée avec succès", "Erreur de modification");
        sy.affichage(jTable1, "SELECT * FROM v_physique ORDER BY CODE DESC");
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        int idr = sy.Chargerid(jComboBox1, "v_identite", "id");
        sy.insertionPhysique(id, idr, Home.admin1, temp, fc, fr, sa02, mensuration, taille, ta, pouls, etat, peau, aire, sphere, thorax, abdomen, organe, apareil, examen, resumer, hypothese, "exec sp_physique ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", "Physique Identifié", "Erreur d'enregistrement");
        sy.affichage(jTable1, "SELECT * FROM v_physique ORDER BY CODE DESC");

    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        sy.Delete(id, "delete from v_physique WHERE code=?");
        sy.affichage(jTable1, "SELECT * FROM v_physique ORDER BY CODE DESC");
        id.setText("");
        temp.setText("");
        fc.setText("");
        fr.setText("");
        sa02.setText("");
        mensuration.setText("");
        taille.setText("");
        ta.setText("");
        pouls.setText("");
        etat.setText("");
        peau.setText("");
        aire.setText("");
        sphere.setText("");
        thorax.setText("");
        abdomen.setText("");
        organe.setText("");
        apareil.setText("");
        examen.setText("");
        resumer.setText("");
        hypothese.setText("");
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        sy.selection(jTable1, id, jComboBox1, Home.admin1, temp, fc, fr, sa02, mensuration, taille, ta, pouls, etat, peau, aire, sphere, thorax, abdomen, organe, apareil, examen, resumer, hypothese);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        String c = "Anamnese",
                req = "SELECT IDENTITE.NOM,postnom,prenom,SEXE,DATE_NAISSance,AGE,ADRESSE,PROVEnNANCE,curatif,mat,echo,cpn,autres,num_mensuel,num_annuel,num_fiche,date_du_jour,IDENTITE.agent\n"
                + ",motif,HISTORIQUE,SUIVIE_GROSSesse,CIRCONSTANCE,ALIMENTATION,BCG,DATE1,NUM_LOT,DTC_HeP_Bib2,DATE2,NUM_LOT2,Pneumo_2,DATE3,\n"
                + "NUM_LOT3,VPOb_0,DATE4,NUM_LOT4,VPOb_1,DATE6,NUM_LOT6,VIP_3,DATE5,NUM_LOT5,VPOb_2,DATE8,NUM_LOT8,VAR_,DATE9,NUM_LOT9,DTC_HeP_Bib3,DATE7,NUM_LOT7,\n"
                + "A_2MOIS,A_3MOIS,A_6MOIS,A_9MOIS,A_12_15MOIS,A_24MOIS,ANTECEDENT,ENVIRONNEMENT,COMPLEMENT,temp,fc,fr,sa02,mensuration_poids,taille,ta,pouls,etat_gen,\n"
                + "PEaU,aires_gangl,sphere_orl,thorax,abdomen,organe_genitaux,APPAREIL_LOCO,examen_neuro,RESUME_SYDRO,HYPOTHESES,resumes FROM IDENTITE INNER JOIN AnamnSuivant\n"
                + " ON  IDENTITE.ID=AnamnSuivant .ID_PERSONNE inner join PHYSIQUE on IDENTITE.ID=PHYSIQUE.CODE_PERS\n"
                + "LEFT join observation on identite.id=observation.id_personne where PHYSIQUE.id='" + id.getText() + "'";
        try {
             sy.EtatSortie(req,c);
        } catch (Exception e) {
        }
        id.setText("");
        temp.setText("");
        fc.setText("");
        fr.setText("");
        sa02.setText("");
        mensuration.setText("");
        taille.setText("");
        ta.setText("");
        pouls.setText("");
        etat.setText("");
        peau.setText("");
        aire.setText("");
        sphere.setText("");
        thorax.setText("");
        abdomen.setText("");
        organe.setText("");
        apareil.setText("");
        examen.setText("");
        resumer.setText("");
        hypothese.setText("");
    }//GEN-LAST:event_jLabel41MouseClicked

    private void rechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechKeyReleased
        sy.AllReseach(jTable1, "select * from v_physique where [NOM PATIENT] like '%" + rech.getText() + "%' or ORGANE_GENITAUX like '%" + rech.getText() + "%'");
    }//GEN-LAST:event_rechKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abdomen;
    private javax.swing.JTextField aire;
    private javax.swing.JTextField apareil;
    private javax.swing.JTextField etat;
    private javax.swing.JTextField examen;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField fr;
    private javax.swing.JTextField hypothese;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mensuration;
    private javax.swing.JTextField organe;
    private javax.swing.JTextField peau;
    private javax.swing.JTextField pouls;
    public static javax.swing.JPanel pphysique;
    private org.jdesktop.swingx.JXSearchField rech;
    private javax.swing.JTextField resumer;
    private javax.swing.JTextField sa02;
    private javax.swing.JTextField sphere;
    private javax.swing.JTextField ta;
    private javax.swing.JTextField taille;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField thorax;
    // End of variables declaration//GEN-END:variables
}
