/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Honore
 */
public class Produit extends javax.swing.JPanel {

    /**
     * Creates new form Pharmacie
     */
    Syncronisation.Syncroniser sy = new Syncronisation.Syncroniser();

    public Produit() {
        initComponents();
        jPanel2.setBackground(new Color(54, 175, 231));
        jPanel1.setBackground(new Color(54, 175, 231));
        Level.setBackground(new Color(54, 175, 231));
        sy.affichage(Pharmacie, "SELECT * FROM PHARMACIE");
        quantite.setVisible(false);
        id.setVisible(false);
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtproduit = new javax.swing.JTextField();
        txtprovenanance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtreference = new javax.swing.JTextField();
        txtEntree = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNLot = new javax.swing.JTextField();
        txtDossage = new javax.swing.JTextField();
        condition = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        forme1 = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantite = new javax.swing.JTextField();
        save = new javax.swing.JLabel();
        Level = new javax.swing.JPanel();
        titreAlerte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pharmacie = new javax.swing.JTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        approv1 = new javax.swing.JLabel();
        approv2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Pharmacie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "STOCK PHARMACIE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Nom du produit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        txtproduit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtproduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 240, 30));
        jPanel1.add(txtprovenanance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("Qté Entrée");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));
        jPanel1.add(txtreference, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 240, 30));

        txtEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntreeActionPerformed(evt);
            }
        });
        txtEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntreeKeyTyped(evt);
            }
        });
        jPanel1.add(txtEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 240, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 102));
        jLabel15.setText("N° lot");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("Date d'entrée");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("Date d'expiration");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 110, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Dosage");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, 30));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 102));
        jLabel17.setText("Conditionnement");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 110, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("Povenance");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Référence");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));
        jPanel1.add(txtNLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 240, 30));
        jPanel1.add(txtDossage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 250, 30));
        jPanel1.add(condition, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 250, 30));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("Prix de d'achat ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });
        jPanel1.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, 30));

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 250, 30));

        jDateChooser3.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 250, 30));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("Forme");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, 30));
        jPanel1.add(forme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 250, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 10));

        quantite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantite.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrer la quantité à approvisioner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.add(quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 250, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 790, 240));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 204));
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Enregistrer");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        save.setOpaque(true);
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, 40));

        Level.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Level.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titreAlerte.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Level.add(titreAlerte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 96, 336, 27));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Level.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 38, 73, 40));

        jPanel2.add(Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 340, 220));

        Pharmacie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Pharmacie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PharmacieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Pharmacie);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1110, 280));

        jXSearchField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXSearchField1KeyReleased(evt);
            }
        });
        jPanel2.add(jXSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 290, 30));

        approv1.setBackground(new java.awt.Color(255, 255, 255));
        approv1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        approv1.setForeground(new java.awt.Color(0, 0, 204));
        approv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        approv1.setText("Approvisioner");
        approv1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        approv1.setOpaque(true);
        approv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approv1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approv1MouseExited(evt);
            }
        });
        jPanel2.add(approv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, 40));

        approv2.setBackground(new java.awt.Color(255, 255, 255));
        approv2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        approv2.setForeground(new java.awt.Color(0, 0, 204));
        approv2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        approv2.setText("Liste des produits");
        approv2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        approv2.setOpaque(true);
        approv2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approv2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approv2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approv2MouseExited(evt);
            }
        });
        jPanel2.add(approv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 160, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        //int id=sy.Chargerid(jLabel1, "", "");
        //int id=Integer.parseInt(jLabel1.getText());
        sy.pharmacie(id, txtproduit, txtprovenanance, txtreference, txtEntree, prix, txtNLot, jDateChooser3, jDateChooser2, txtDossage, forme1, condition);
        sy.affichage(Pharmacie, "SELECT * FROM PHARMACIE");
        txtproduit.setText("");
        txtprovenanance.setText("");
        txtreference.setText("");
        txtEntree.setText("");
        prix.setText("");
        txtNLot.setText("");
        txtDossage.setText("");
        forme1.setText("");
        condition.setText("");
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered

    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited

    }//GEN-LAST:event_saveMouseExited

    private void PharmacieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PharmacieMouseClicked
        sy.selectionApro(id, txtproduit, txtprovenanance, txtreference,
                txtEntree, prix, txtNLot, jDateChooser3, jDateChooser2,
                txtDossage, forme1, condition, Pharmacie);
        quantite.setVisible(true);
    }//GEN-LAST:event_PharmacieMouseClicked

    private void txtEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntreeActionPerformed

    private void approv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv1MouseClicked
        if (quantite.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Entrer la quantité à approvisionner");
            quantite.setVisible(true);
        } else {
            sy.upgradeappro(quantite, id);
            quantite.setText("");
            sy.affichage(Pharmacie, "SELECT * FROM PHARMACIE");
            quantite.setVisible(false);
        }
    }//GEN-LAST:event_approv1MouseClicked

    private void approv1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_approv1MouseEntered

    private void approv1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_approv1MouseExited

    private void approv2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv2MouseClicked
        String c = "ListeProduit",
                req = "select * from pharmacie";
        try {
            sy.EtatSortie(req, c);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_approv2MouseClicked

    private void approv2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_approv2MouseEntered

    private void approv2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approv2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_approv2MouseExited

    private void jXSearchField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearchField1KeyReleased
        sy.AllReseach(Pharmacie, "select * from pharmacie where NOM_PRODUIT LIKE '%" + jXSearchField1.getText() + "%'");               // TODO add your handling code here:
    }//GEN-LAST:event_jXSearchField1KeyReleased

    private void txtEntreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntreeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEntreeKeyTyped

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_prixKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Level;
    private javax.swing.JTable Pharmacie;
    private javax.swing.JLabel approv1;
    private javax.swing.JLabel approv2;
    private javax.swing.JTextField condition;
    private javax.swing.JTextField forme1;
    private javax.swing.JLabel id;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField quantite;
    private javax.swing.JLabel save;
    private javax.swing.JLabel titreAlerte;
    private javax.swing.JTextField txtDossage;
    private javax.swing.JTextField txtEntree;
    private javax.swing.JTextField txtNLot;
    private javax.swing.JTextField txtproduit;
    private javax.swing.JTextField txtprovenanance;
    private javax.swing.JTextField txtreference;
    // End of variables declaration//GEN-END:variables
}
