/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;

/**
 *
 * @author BIENFAIT
 */
public class Rapport extends javax.swing.JPanel {

    /**
     * Creates new form Rapport
     */
    
      
    Syncronisation.Syncroniser t = new Syncronisation.Syncroniser();
    public Rapport() {
        initComponents();
        // jPanel1.setBackground(new Color(192, 192, 255));
        jPanel2.setBackground(new Color(54, 175, 231));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        consult = new javax.swing.JLabel();
        labo = new javax.swing.JLabel();
        pharma = new javax.swing.JLabel();
        hospital = new javax.swing.JLabel();
        nebil = new javax.swing.JLabel();
        cigna = new javax.swing.JLabel();
        imagerie = new javax.swing.JLabel();
        sortie = new javax.swing.JLabel();
        kine = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dette = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totg = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        totallivre = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Rapport mensuel des entrés et sorties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, 22));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LABORATOIRE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 81, 101, 22));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PHARMACIE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 81, 101, 22));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KINE");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 102, 22));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NEBULISATION");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 81, 103, 22));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HOSPITALISATION");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 81, 125, 22));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SORTIE");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 81, 102, 22));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("IMAGERIE");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 81, 88, 22));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CIGNA");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 81, 112, 22));

        consult.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        consult.setForeground(new java.awt.Color(51, 51, 255));
        consult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consult.setText("TOTAL");
        jPanel2.add(consult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 107, 91));

        labo.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        labo.setForeground(new java.awt.Color(51, 51, 255));
        labo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labo.setText("TOTAL");
        jPanel2.add(labo, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 162, 102, 91));

        pharma.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        pharma.setForeground(new java.awt.Color(51, 51, 255));
        pharma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pharma.setText("TOTAL");
        jPanel2.add(pharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 162, 102, 91));

        hospital.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        hospital.setForeground(new java.awt.Color(51, 51, 255));
        hospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospital.setText("TOTAL");
        jPanel2.add(hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 162, 125, 91));

        nebil.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        nebil.setForeground(new java.awt.Color(51, 51, 255));
        nebil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nebil.setText("TOTAL");
        jPanel2.add(nebil, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 162, 103, 91));

        cigna.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        cigna.setForeground(new java.awt.Color(51, 51, 255));
        cigna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cigna.setText("TOTAL");
        jPanel2.add(cigna, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 162, 107, 91));

        imagerie.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        imagerie.setForeground(new java.awt.Color(51, 51, 255));
        imagerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagerie.setText("TOTAL");
        jPanel2.add(imagerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 162, 107, 91));

        sortie.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        sortie.setForeground(new java.awt.Color(51, 51, 255));
        sortie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sortie.setText("TOTAL");
        jPanel2.add(sortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 162, 102, 91));

        kine.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        kine.setForeground(new java.awt.Color(51, 51, 255));
        kine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kine.setText("TOTAL");
        jPanel2.add(kine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, 102, 91));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("$");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 109, 56, 47));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("$");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 109, 56, 47));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("$");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 109, 56, 47));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("$");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 109, 56, 47));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("$");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 109, 56, 47));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("$");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 109, 56, 47));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("$");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 310, 56, 47));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("$");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 310, 56, 47));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("$");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 109, 56, 47));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("$");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 109, 56, 47));

        credit.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        credit.setForeground(new java.awt.Color(51, 51, 255));
        credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credit.setText("TOTAL");
        jPanel2.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 363, 102, 91));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CREDIT");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 282, 102, 22));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("$");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 310, 56, 47));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DETTE");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 282, 102, 22));

        dette.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        dette.setForeground(new java.awt.Color(51, 51, 255));
        dette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dette.setText("TOTAL");
        jPanel2.add(dette, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 363, 102, 91));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("$");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 327, 56, 47));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TOTAL MENSUEL");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 299, 148, 22));

        totg.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        totg.setForeground(new java.awt.Color(255, 0, 0));
        totg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totg.setText("TOTAL");
        jPanel2.add(totg, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 395, 260, 120));

        date1.setDateFormatString("yyyy-MM-dd");
        date1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date1PropertyChange(evt);
            }
        });
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 190, 30));

        date2.setDateFormatString("yyyy-MM-dd");
        date2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date2PropertyChange(evt);
            }
        });
        jPanel2.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 45, 200, 30));

        totallivre.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        totallivre.setForeground(new java.awt.Color(51, 51, 255));
        totallivre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totallivre.setText("TOTAL");
        jPanel2.add(totallivre, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 363, 102, 91));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("$");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 310, 56, 47));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TOTAL LIVRE");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(78, 14));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 282, 102, 22));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void date1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date1PropertyChange
        t.RapportTot("facture", "TOTAL", "date_", totg, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "dette", "DATE_OPERATION", dette, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "credit", "DATE_OPERATION", credit, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", totallivre, date1, date2);
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", consult, date1, date2, "consultation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", labo, date1, date2, "labo");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", pharma, date1, date2, "pharmacie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", kine, date1, date2, "Kine");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", nebil, date1, date2, "nébulisation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", hospital, date1, date2, "hospitalisation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", sortie, date1, date2, "sortie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", imagerie, date1, date2, "Imagerie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", cigna, date1, date2, "cigna");
    }//GEN-LAST:event_date1PropertyChange

    private void date2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date2PropertyChange
        t.RapportTot("facture", "TOTAL", "date_", totg, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "dette", "DATE_OPERATION", dette, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "credit", "DATE_OPERATION", credit, date1, date2);
        t.RapportTot("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", totallivre, date1, date2);
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", consult, date1, date2, "consultation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", labo, date1, date2, "labo");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", pharma, date1, date2, "pharmacie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", kine, date1, date2, "Kine");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", nebil, date1, date2, "nébulisation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", hospital, date1, date2, "hospitalisation");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", sortie, date1, date2, "sortie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", imagerie, date1, date2, "Imagerie");
        t.RapportLibelle("LIVRE_DE_CAISSE", "montant", "DATE_OPERATION", cigna, date1, date2, "cigna");
    }//GEN-LAST:event_date2PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cigna;
    private javax.swing.JLabel consult;
    private javax.swing.JLabel credit;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JLabel dette;
    private javax.swing.JLabel hospital;
    private javax.swing.JLabel imagerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kine;
    private javax.swing.JLabel labo;
    private javax.swing.JLabel nebil;
    private javax.swing.JLabel pharma;
    private javax.swing.JLabel sortie;
    private javax.swing.JLabel totallivre;
    private javax.swing.JLabel totg;
    // End of variables declaration//GEN-END:variables
}
